[workspace]
resolver = "2"
members = [
    "crates/kiln-hal",
    "crates/kiln-models",
    "crates/kiln-mem",
    "crates/kiln-io",
    "crates/kiln-core",
    "crates/kiln-api",
    "crates/kiln-cli",
    "crates/kiln-runtime",
    "crates/kiln-bench",
    "crates/kiln-kernels",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["Andrei Path"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
cc = "1"
