[workspace]
resolver = "2"
members = [
    "crates/kiln-hal",
    "crates/kiln-models",
    "crates/kiln-mem",
    "crates/kiln-io",
    "crates/kiln-core",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["Andrei Path"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
